import './globals.css'
import { Providers } from './providers'
import { NextIntlClientProvider, useMessages } from "next-intl";

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children,
  params: { locale }

}: {
  children: React.ReactNode
  params: { locale: string };

}) {


  const messages = useMessages();
  return (
    <html lang={locale} dir={locale === "he" ? "rtl" : "ltr"}>
      <NextIntlClientProvider
        locale={locale}
        messages={messages}
      >
        <body>
          <Providers>{children}</Providers>
        </body>
      </NextIntlClientProvider>
    </html>
  )
}